# Generated by Django 3.2.6 on 2021-08-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='happy_clients',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='hours_of_support',
            field=models.IntegerField(blank=True),
        ),
    ]
