# Generated by Django 3.2.6 on 2021-08-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210818_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_data', to='core.siteinfo'),
        ),
    ]
