# Generated by Django 3.2.6 on 2021-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210818_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='resume',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
