# Generated by Django 3.2.6 on 2021-08-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.resumedata'),
        ),
    ]
