# Generated by Django 3.2.6 on 2021-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210818_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='bio',
            field=models.TextField(blank=True, help_text='tell us something about yourself...'),
        ),
    ]
