# Generated by Django 3.2.6 on 2021-08-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resumedata_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(default='index.png', upload_to=''),
            preserve_default=False,
        ),
    ]
