# Generated by Django 3.2.6 on 2021-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
